name: "NXNavigationExtension CI"

on: [push, pull_request]

jobs:
  Pods:
    name: CocoaPods Lint
    runs-on: macOS-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.0.app
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Switch Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Install CocoaPods
        run: gem install cocoapods --no-document --quiet

      - name: Install Xcpretty
        run: gem install xcpretty --no-document --quiet

      - name: Run NXNavigationExtension podspec lint
        run: |
          set -o pipefail
          pod lib lint *.podspec --allow-warnings --skip-tests

  Demo:
    name: Run Demo
    runs-on: macOS-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.0.app
      WORKSPACE_NAME: NXNavigationExtension.xcworkspace
    strategy:
      matrix:
        swift_version: ["6.0"]
        scheme:
          - NXNavigationExtensionDemo
        iosDestination: ["OS=18.0,name=iPhone 16 Pro"]
        macCatalystDestination: ["platform=macOS,arch=x86_64,variant=Mac Catalyst"]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Switch Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Run Demo
        run: |
          set -o pipefail
          xcodebuild build -workspace "${{ env.WORKSPACE_NAME }}" -scheme "${{ matrix.scheme }}" -destination "${{ matrix.iosDestination }}" -configuration Debug CODE_SIGNING_ALLOWED=NO | xcpretty -c
          xcodebuild build -workspace "${{ env.WORKSPACE_NAME }}" -scheme "${{ matrix.scheme }}" -destination "${{ matrix.macCatalystDestination }}" -configuration Debug CODE_SIGNING_ALLOWED=NO | xcpretty -c

  Build:
    name: Build Library
    runs-on: macOS-15
    env:
      DEVELOPER_DIR: /Applications/Xcode_16.0.app
      WORKSPACE_NAME: NXNavigationExtension.xcworkspace
    strategy:
      matrix:
        swift_version: ["6.0"]
        scheme:
          - NXNavigationExtension
          - NXNavigationExtensionSwiftUI

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Switch Xcode
        run: sudo xcode-select -s /Applications/Xcode_16.0.app

      - name: Build as dynamic frameworks
        run: |
          set -o pipefail
          xcodebuild build -workspace "${{ env.WORKSPACE_NAME }}" -scheme "${{ matrix.scheme }}" -sdk iphonesimulator PLATFORM_NAME=iphonesimulator -configuration Release CODE_SIGNING_ALLOWED=NO | xcpretty -c
          xcodebuild build -workspace "${{ env.WORKSPACE_NAME }}" -scheme "${{ matrix.scheme }}" -destination "platform=macOS,arch=x86_64,variant=Mac Catalyst" -configuration Release CODE_SIGNING_ALLOWED=NO | xcpretty -c
          rm -rf ~/Library/Developer/Xcode/DerivedData/
